dist: bionic
language: nodejs
nodejs: 15
install: skip
group: edge
script:
  - node -v
  - nvm --version
  - npm --version
  - strings /lib/powerpc64le-linux-gnu/libc.so.6 | grep GLIBC || true
  - strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC || true
  - npm install git-latest-semver-tag
  
jobs:
  include: 
    - arch: ppc64le   
    - arch: amd64
